name: Update Metrics
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lowlighter/metrics/tree/7d7297fcbe2e329068d2731eb0390808da68d5fc
      - uses: lowlighter/metrics@7d7297fcbe2e329068d2731eb0390808da68d5fc
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_gist: 5d4fc4a95d67eb80a9dbea0dd6e85745
          output_action: 'gist'
          
          user: arthurfiorette
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          plugin_followup: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_lines: yes
          plugin_traffic: yes
